name: Build and Release Executables

on:
  push:
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pynput==1.7.7 PyYAML==6.0.1

    - name: Build executable
      run: |
        pyinstaller --onefile --hidden-import=pynput.keyboard._xorg scripts/main.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-executable
        path: dist/

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Get version
      id: get_version
      run: echo "::set-output name=version::${GITHUB_REF##*/}"

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      id: create_release
      uses: actions/create-release@v1.1.4
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Download Ubuntu Artifact
      uses: actions/download-artifact@v4
      with:
        name: ubuntu-latest-executable
        path: dist/ubuntu-latest

    - name: Upload Ubuntu Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/ubuntu-latest/main
        asset_name: keyseq-${{ steps.get_version.outputs.version }}.linux
        asset_content_type: application/octet-stream

    - name: Download MacOS Artifact
      uses: actions/download-artifact@v4
      with:
        name: macos-latest-executable
        path: dist/macos-latest

    - name: Upload MacOS Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/macos-latest/main
        asset_name: keyseq-${{ steps.get_version.outputs.version }}.mac
        asset_content_type: application/octet-stream

    - name: Download Windows Artifact
      uses: actions/download-artifact@v4
      with:
        name: windows-latest-executable
        path: dist/windows-latest

    - name: Upload Windows Release Asset
      if: startsWith(github.ref, 'refs/tags/')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: dist/windows-latest/main.exe
        asset_name: keyseq-${{ steps.get_version.outputs.version }}.windows.exe
        asset_content_type: application/octet-stream
